[ERSSUP-76095]-[DW]-[Added support for accessing the APIs via CIS 2 with an authentication assurance level of 2]-[JW]

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -17,7 +17,7 @@ echo "XML files to format:"
 echo "$xmlFilesToFormat"
 for sourceFilePath in $xmlFilesToFormat
 do
-  poetry run xmlformat --indent 4 --eof-newline --overwrite --selfclose --infile "$(pwd)/$sourceFilePath"
+  poetry run xmlformat --indent 4 --eof-newline --overwrite --selfclose --infile "$(pwd)/$sourceFilePath" || echo "$(pwd)/$sourceFilePath" is invalid.
   git add $sourceFilePath
 done
 
